[versions]
flink = "1.20.0"
flink-kinesis = "5.0.0-1.20"

[libraries]
flink-streaming = { module = "org.apache.flink:flink-streaming-java", version.ref = "flink" }

# Bridge between Stream and Table APIs
flink-table-bridge = { module = "org.apache.flink:flink-table-api-java-bridge", version.ref = "flink" }
flink-table-planner = { module = "org.apache.flink:flink-table-planner_2.12", version.ref = "flink" }

# Flink client APIs (e.g. submit jobs to a Flink cluster (i.e. our main class)
flink-clients = { module = "org.apache.flink:flink-clients", version.ref = "flink" }

flink-json = { module = "org.apache.flink:flink-json", version.ref = "flink" }

# Connectors
flink-connector-base = { module = "org.apache.flink:flink-connector-base", version.ref = "flink" }
flink-kinesis = { module = "org.apache.flink:flink-connector-aws-kinesis-streams", version.ref = "flink-kinesis" }
